---
- hosts: all
  user: root
  become: true
  vars:
    glusterfs_ppa_use: false
    disk_additional_disks:
      - disk: /dev/vdb
        fstype: ext4
        mount_options: defaults
        mount: /data

  pre_tasks:
    - name: Clear file
      command: rm -rf /etc/apt/apt.conf.d/50unattended-upgrades*

  roles:
    - GoContainer.system-update
    - AerisCloud.disk
    - GoContainer.glusterfs
