---
- hosts: all
  user: root
  become: true
  vars:
    glusterfs_ppa_use: false
    gluster_mount_dir: /mnt/data
    gluster_brick_dir: /srv/gluster/brick
    gluster_brick_name: gluster

  roles:
    - GoContainer.system-update
    - GoContainer.glusterfs
